### ISSUE TITLE
DV needs installer update 6.1.0

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/dv-brms-integration-demo#9]
Needs to update to: jboss-dv-installer-6.1.0.Beta-redhat-1.jar

**Comment by jmarley** [comment]
fyi, the autofile schema for jdv 6.1 is different and so is how/where jdv handles users and roles. I have an example of the autofile in my project (https://github.com/jmarley/dv-federation-demo/tree/master/support), but was waiting to talk with you guys on how to handle this multiple versions of the autofile as well as the user/roles settings. 

The way I see it is we have to manage 2 auto installer files, keeping the teiid-security-{roles,users}.properties files in place isn't going to hurt anything, but isn't needed for jdv 6.1 since this information is stored in the application-{usrs,roles}.properies. Thoughts?

**Comment by kpeeples** [comment]
Yes my input is have 2 auto installers with the script checking the product name to determine which auto installer file to use.  Also If someone has time to upgrade to Beta then that would be good otherwise I will make the changes for 6.1 GA/

**Comment by eschabell** [comment]
Released! 

https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=data.services.platform&productChanged=yes

**Comment by kpeeples** [comment]
I started looking at updating to 6.1.

**Comment by eschabell** [comment]
Giving up on this. ;-)
